openapi: 3.0.0
info:
  title: 'AI-SPRINT Monitoring Subsystem (AMS) RESTful API'
  version: '1.0'
servers:
  - url: /monitoring/
paths:
  /execution_time/session/<session_id>:
    get:
      operationId: app.session_exec_time
      responses:
        200:
          description: 'get a single session execution time'
  /execution_time/components/<specifier>:
    get:
      operationId: app.components_exec_time
      responses:
        200:
          description: 'get a single component or component path execution time'
  /throughput/:
    get:
      operationId: app.system_throughput
      responses:
        200:
          description: 'get system throughput'
